const moonPhaseList = [
 'wi-moon-alt-new',
 'wi-moon-alt-waxing-crescent-1',
 'wi-moon-alt-waxing-crescent-2',
 'wi-moon-alt-waxing-crescent-3',
 'wi-moon-alt-waxing-crescent-4',
 'wi-moon-alt-waxing-crescent-5',
 'wi-moon-alt-waxing-crescent-6',
 'wi-moon-alt-first-quarter',
 'wi-moon-alt-waxing-gibbous-1',
 'wi-moon-alt-waxing-gibbous-2',
 'wi-moon-alt-waxing-gibbous-3',
 'wi-moon-alt-waxing-gibbous-4',
 'wi-moon-alt-waxing-gibbous-5',
 'wi-moon-alt-waxing-gibbous-6',
 'wi-moon-alt-full',
 'wi-moon-alt-waning-gibbous-1',
 'wi-moon-alt-waning-gibbous-2',
 'wi-moon-alt-waning-gibbous-3',
 'wi-moon-alt-waning-gibbous-4',
 'wi-moon-alt-waning-gibbous-5',
 'wi-moon-alt-waning-gibbous-6',
 'wi-moon-alt-third-quarter',
 'wi-moon-alt-waning-crescent-1',
 'wi-moon-alt-waning-crescent-2',
 'wi-moon-alt-waning-crescent-3',
 'wi-moon-alt-waning-crescent-4',
 'wi-moon-alt-waning-crescent-5',
 'wi-moon-alt-waning-crescent-6',
 'wi-moon-alt-new',
];

const moonPhaseName = [
    'New Moon ',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'First Quarter Moon',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Full Moon',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Third Quarter Moon',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'New Moon',
   ];


export {moonPhaseList, moonPhaseName}